In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from  sklearn.linear_model import LinearRegression
import statsmodels.api as sm
import math
import random # necessário para utilizar o módulo random

In [2]:
#  DADOS - EXPERIMENTAL
CONTEXP000_CS137_0662 = 9454
CONTEXP002_CS137_0662 = 9485
CONTEXP008_CS137_0662 = 8606
CONTEXP014_CS137_0662 = 8225
CONTEXP000_AM241_00595 = 594
CONTEXP002_AM241_00595 = 548
CONTEXP008_AM241_00595 = 592
CONTEXP014_AM241_00595 = 224


# DADOS - TEORIA (PENCIL-BEAM)

CONTPBEAM000_CS137_0662 = 4403330
CONTPBEAM002_CS137_0662 = 4313390
CONTPBEAM008_CS137_0662 = 4026930
CONTPBEAM014_CS137_0662 = 3764660
CONTPBEAM000_AM241_00595 = 8056020
CONTPBEAM002_AM241_00595 = 7645430
CONTPBEAM008_AM241_00595 = 6531960
CONTPBEAM014_AM241_00595 = 5578480

# DADOS - TEORIA (ISOTRÓPICO)

CONTISO000_CS137_0662 = 3361
CONTISO002_CS137_0662 = 3200
CONTISO008_CS137_0662 = 3118
CONTISO014_CS137_0662 = 2807
CONTISO000_AM241_00595 = 7928
CONTISO002_AM241_00595 = 7477
CONTISO008_AM241_00595 = 6635
CONTISO014_AM241_00595 = 5901

In [3]:
# Calculo da Intensidade - Coeficiente Linear de Atenuação


# CS-137 (EXPERIMENTAL)


# I_CS137_PLA002

PICO1_PLACS137_EXP002 = CONTEXP002_CS137_0662/CONTEXP000_CS137_0662
print(PICO1_PLACS137_EXP002)

INVPICO1_PLACS137_EXP002 = CONTEXP000_CS137_0662/CONTEXP002_CS137_0662
print(INVPICO1_PLACS137_EXP002)

# I_CS137_PLA008

PICO1_PLACS137_EXP008 = CONTEXP008_CS137_0662/CONTEXP000_CS137_0662
print(PICO1_PLACS137_EXP008)

INVPICO1_PLACS137_EXP008 = CONTEXP000_CS137_0662/CONTEXP008_CS137_0662
print(INVPICO1_PLACS137_EXP008)

# I_CS137_PLA014

PICO1_PLACS137_EXP014 = CONTEXP014_CS137_0662/CONTEXP000_CS137_0662
print(PICO1_PLACS137_EXP014)

INVPICO1_PLACS137_EXP014 = CONTEXP000_CS137_0662/CONTEXP014_CS137_0662
print(INVPICO1_PLACS137_EXP014)


1.0032790353289613
0.9967316816025303
0.91030251745293
1.0985359051824308
0.8700021155066638
1.1494224924012157


In [4]:
# Calculo da Intensidade - Coeficiente Linear de Atenuação

# AM-241 (EXPERIMENTAL)

# I_AM241_PLA002

PICO1_PLAAM241_EXP002 = CONTEXP002_AM241_00595/CONTEXP000_AM241_00595
print(PICO1_PLAAM241_EXP002)

INVPICO1_PLAAM241_EXP002 = CONTEXP000_AM241_00595/CONTEXP002_AM241_00595
print(INVPICO1_PLAAM241_EXP002)


# I_AM241_PLA008

PICO1_PLAAM241_EXP008 = CONTEXP008_AM241_00595/CONTEXP000_AM241_00595
print(PICO1_PLAAM241_EXP008)

INVPICO1_PLAAM241_EXP008 = CONTEXP000_AM241_00595/CONTEXP008_AM241_00595
print(INVPICO1_PLAAM241_EXP008)

# I_AM241_PLA014

PICO1_PLAAM241_EXP014 = CONTEXP014_AM241_00595/CONTEXP000_AM241_00595
print(PICO1_PLAAM241_EXP014)

INVPICO1_PLAAM241_EXP014 = CONTEXP000_AM241_00595/CONTEXP014_AM241_00595
print(INVPICO1_PLAAM241_EXP014)

0.9225589225589226
1.083941605839416
0.9966329966329966
1.0033783783783783
0.3771043771043771
2.6517857142857144


In [5]:
# VALOR NORMAL

# CS-137 (EXPERIMENTAL)

print(PICO1_PLACS137_EXP002)
print(PICO1_PLACS137_EXP008)
print(PICO1_PLACS137_EXP014)

# AM-241 (EXPERIMENTAL)

print(PICO1_PLAAM241_EXP002)
print(PICO1_PLAAM241_EXP008)
print(PICO1_PLAAM241_EXP014)

1.0032790353289613
0.91030251745293
0.8700021155066638
0.9225589225589226
0.9966329966329966
0.3771043771043771


In [6]:
# VALOR INVERSO

# CS-137 (EXPERIMENTAL)

print(INVPICO1_PLACS137_EXP002)
print(INVPICO1_PLACS137_EXP008)
print(INVPICO1_PLACS137_EXP014)

# AM-241 (EXPERIMENTAL)

print(INVPICO1_PLAAM241_EXP002)
print(INVPICO1_PLAAM241_EXP008)
print(INVPICO1_PLAAM241_EXP014)

0.9967316816025303
1.0985359051824308
1.1494224924012157
1.083941605839416
1.0033783783783783
2.6517857142857144


In [7]:
#CS-137 (PENCIL BEAM)

PICO1_PLACS137_PBEAM002=CONTPBEAM002_CS137_0662/CONTPBEAM000_CS137_0662
print(PICO1_PLACS137_PBEAM002)

INVPICO1_PLACS137_PBEAM002=CONTISO000_CS137_0662/CONTISO002_CS137_0662
print(INVPICO1_PLACS137_PBEAM002)

PICO1_PLACS137_PBEAM008=CONTPBEAM008_CS137_0662/CONTPBEAM000_CS137_0662
print(PICO1_PLACS137_PBEAM008)

INVPICO1_PLACS137_PBEAM008=CONTISO000_CS137_0662/CONTISO008_CS137_0662
print(INVPICO1_PLACS137_PBEAM008)

PICO1_PLACS137_PBEAM014=CONTPBEAM014_CS137_0662/CONTPBEAM000_CS137_0662
print(PICO1_PLACS137_PBEAM014)

INVPICO1_PLACS137_PBEAM014=CONTISO000_CS137_0662/CONTISO014_CS137_0662
print(INVPICO1_PLACS137_PBEAM014)


0.9795745492615816
1.0503125
0.9145192388487804
1.0779345734445158
0.8549574980753203
1.1973637335233345


In [8]:
#AM-241 (PENCIL BEAM)

PICO1_PLAAM241_PBEAM002=CONTPBEAM002_AM241_00595/CONTPBEAM000_AM241_00595
print(PICO1_PLAAM241_PBEAM002)

INVPICO1_PLAAM241_PBEAM002=CONTPBEAM000_AM241_00595/CONTPBEAM002_AM241_00595
print(INVPICO1_PLAAM241_PBEAM002)

PICO1_PLAAM241_PBEAM008=CONTPBEAM008_AM241_00595/CONTPBEAM000_AM241_00595
print(PICO1_PLAAM241_PBEAM008)

INVPICO1_PLAAM241_PBEAM008=CONTPBEAM000_AM241_00595/CONTPBEAM008_AM241_00595
print(INVPICO1_PLAAM241_PBEAM008)

PICO1_PLAAM241_PBEAM014=CONTPBEAM014_AM241_00595/CONTPBEAM000_AM241_00595
print(PICO1_PLAAM241_PBEAM014)

INVPICO1_PLAAM241_PBEAM014=CONTPBEAM000_AM241_00595/CONTPBEAM014_AM241_00595
print(INVPICO1_PLAAM241_PBEAM014)


0.9490331453993411
1.0537039774087265
0.8108172521915288
1.233323535355391
0.6924610415565006
1.4441245643974703


In [9]:
# CÉSIO-137 (ISOTRÓPICO)

PICO1_PLACS137_ISO002=CONTISO002_CS137_0662/CONTISO000_CS137_0662
print(PICO1_PLACS137_ISO002)

INVPICO1_PLACS137_ISO002=CONTISO000_CS137_0662/CONTISO002_CS137_0662
print(INVPICO1_PLACS137_ISO002)

PICO1_PLACS137_ISO008=CONTISO008_CS137_0662/CONTISO000_CS137_0662
print(PICO1_PLACS137_ISO008)

INVPICO1_PLACS137_ISO008=CONTISO000_CS137_0662/CONTISO008_CS137_0662
print(INVPICO1_PLACS137_ISO008)

PICO1_PLACS137_ISO014=CONTISO014_CS137_0662/CONTISO000_CS137_0662
print(PICO1_PLACS137_ISO014)

INVPICO1_PLACS137_ISO014=CONTISO000_CS137_0662/CONTISO014_CS137_0662
print(INVPICO1_PLACS137_ISO014)


0.9520975900029753
1.0503125
0.927700089259149
1.0779345734445158
0.8351681047307349
1.1973637335233345


In [10]:
#AM-241 (ISOTRÓPICO)

PICO1_PLAAM241_ISO002=CONTISO002_AM241_00595/CONTISO000_AM241_00595
print(PICO1_PLAAM241_ISO002)

INVPICO1_PLAAM241_ISO002=CONTISO000_AM241_00595/CONTISO002_AM241_00595
print(INVPICO1_PLAAM241_ISO002)

PICO1_PLAAM241_ISO008=CONTISO008_AM241_00595/CONTISO000_AM241_00595
print(PICO1_PLAAM241_ISO008)

INVPICO1_PLAAM241_ISO008=CONTISO000_AM241_00595/CONTISO008_AM241_00595
print(INVPICO1_PLAAM241_ISO008)

PICO1_PLAAM241_ISO014=CONTISO014_AM241_00595/CONTISO000_AM241_00595
print(PICO1_PLAAM241_ISO014)

INVPICO1_PLAAM241_ISO014=CONTISO000_AM241_00595/CONTISO014_AM241_00595
print(INVPICO1_PLAAM241_ISO014)

0.9431130171543896
1.0603183094824127
0.8369071644803229
1.1948756593820649
0.7443239152371343
1.343501101508219


In [11]:
# DADOS DE INTENSIDADE NORMALIZADOS (METROS)

CMESP_CS137_PLA002 = 0.2 # CENTIMETROS # 0.002  # METROS
CMESP_CS137_PLA008 = 0.8 # CENTIMETROS # 0.008 # METROS
CMESP_CS137_PLA014 = 1.4 # CENTIMETROS # 0.014 # METROS 

CMESP_AM241_PLA002 = 0.2 # CENTIMETROS # 0.002 # METROS 
CMESP_AM241_PLA008 = 0.8 # CENTIMETROS # 0.008  # METROS 
CMESP_AM241_PLA014 = 1.4 # CENTIMETROS # 0.014 # METROS 

xCS_ESPCM = [CMESP_CS137_PLA002, CMESP_CS137_PLA008, CMESP_CS137_PLA014]
print(xCS_ESPCM)
xAM_ESPCM =[CMESP_AM241_PLA002, CMESP_AM241_PLA008, CMESP_AM241_PLA014]
print(xAM_ESPCM)

[0.2, 0.8, 1.4]
[0.2, 0.8, 1.4]


In [33]:
# lN (I/I0): CS-137 (EXPERIMENTAL)

LN_PICO1_PLACS137_EXP002 = np.log(PICO1_PLACS137_EXP002)
print(LN_PICO1_PLACS137_EXP002)

LN_INVPICO1_PLACS137_EXP002 = np.log(INVPICO1_PLACS137_EXP002)
print(LN_INVPICO1_PLACS137_EXP002)

LN_PICO1_PLACS137_EXP008 = np.log(PICO1_PLACS137_EXP008)
print(LN_PICO1_PLACS137_EXP008)

LN_INVPICO1_PLACS137_EXP008 = np.log(INVPICO1_PLACS137_EXP008)
print(LN_INVPICO1_PLACS137_EXP008)

LN_PICO1_PLACS137_EXP014 = np.log(PICO1_PLACS137_EXP014)
print(LN_PICO1_PLACS137_EXP014)

LN_INVPICO1_PLACS137_EXP014 = np.log(INVPICO1_PLACS137_EXP014)
print(LN_INVPICO1_PLACS137_EXP014)


0.0032736710159329665
-0.0032736710159328806
-0.09397829795463669
0.09397829795463669
-0.13925963571960903
0.13925963571960898


In [34]:
# lN (I/I0): AM-241 (EXPERIMENTAL)

LN_PICO1_PLAAM241_EXP002 = np.log(PICO1_PLAAM241_EXP002)
print(LN_PICO1_PLAAM241_EXP002)

LN_INVPICO1_PLAAM241_EXP002 = np.log(INVPICO1_PLAAM241_EXP002)
print(LN_INVPICO1_PLAAM241_EXP002)

LN_PICO1_PLAAM241_EXP008 = np.log(PICO1_PLAAM241_EXP008)
print(LN_PICO1_PLAAM241_EXP008)

LN_INVPICO1_PLAAM241_EXP008 = np.log(INVPICO1_PLAAM241_EXP008)
print(LN_INVPICO1_PLAAM241_EXP008)

LN_PICO1_PLAAM241_EXP014 = np.log(PICO1_PLAAM241_EXP014)
print(LN_PICO1_PLAAM241_EXP014)

LN_INVPICO1_PLAAM241_EXP014 = np.log(INVPICO1_PLAAM241_EXP014)
print(LN_INVPICO1_PLAAM241_EXP014)

-0.08060403241462938
0.08060403241462935
-0.00337268447863923
0.003372684478639156
-0.9752332675076051
0.9752332675076051


In [47]:
# lN (I/I0): CS-137 (PENCIL BEAM)

LN_PICO1_PLACS137_PBEAM002 = np.log(PICO1_PLACS137_PBEAM002)
print(LN_PICO1_PLACS137_PBEAM002)

LN_INVPICO1_PLACS137_PBEAM002 = np.log(INVPICO1_PLACS137_PBEAM002)
print(LN_INVPICO1_PLACS137_PBEAM002)

LN_PICO1_PLACS137_PBEAM008 = np.log(PICO1_PLACS137_PBEAM008)
print(LN_PICO1_PLACS137_PBEAM008)

LN_INVPICO1_PLACS137_PBEAM008 = np.log(INVPICO1_PLACS137_PBEAM008)
print(LN_INVPICO1_PLACS137_PBEAM008)

LN_PICO1_PLACS137_PBEAM014 = np.log(PICO1_PLACS137_PBEAM014)
print(LN_PICO1_PLACS137_PBEAM014)

LN_INVPICO1_PLACS137_PBEAM014 = np.log(INVPICO1_PLACS137_PBEAM014)
print(LN_INVPICO1_PLACS137_PBEAM014)


-0.020636934987259024
0.04908773893728773
-0.08935677381232765
0.07504677810738393
-0.1567035211343791
0.18012225136322313


In [49]:
# lN (I/I0): AM-241 (PENCIL BEAM)

LN_PICO1_PLAAM241_PBEAM002 = np.log(PICO1_PLAAM241_PBEAM002)
print(LN_PICO1_PLAAM241_PBEAM002)

LN_INVPICO1_PLAAM241_PBEAM002 = np.log(INVPICO1_PLAAM241_PBEAM002)
print(LN_INVPICO1_PLAAM241_PBEAM002)

LN_PICO1_PLAAM241_PBEAM008 = np.log(PICO1_PLAAM241_PBEAM008)
print(LN_PICO1_PLAAM241_PBEAM008)

LN_INVPICO1_PLAAM241_PBEAM008 = np.log(INVPICO1_PLAAM241_PBEAM008)
print(LN_INVPICO1_PLAAM241_PBEAM008)

LN_PICO1_PLAAM241_PBEAM014 = np.log(PICO1_PLAAM241_PBEAM014)
print(LN_PICO1_PLAAM241_PBEAM014)

LN_INVPICO1_PLAAM241_PBEAM014 = np.log(INVPICO1_PLAAM241_PBEAM014)
print(LN_INVPICO1_PLAAM241_PBEAM014)

-0.05231155432318328
0.05231155432318324
-0.20971258664407325
0.20971258664407322
-0.36750330018330973
0.3675033001833097


In [38]:
# lN (I/I0): CS-137 (ISOTROPICO)

#ln_ISOyCS137_0662 = [LN_PICOISO_PLACS002_0662, LN_PICOISO_PLACS008_0662, LN_PICOISO_PLACS014_0662]
#print(ln_ISOyCS137_0662)

LN_PICO1_PLACS137_ISO002 = np.log(PICO1_PLACS137_ISO002)
print(LN_PICO1_PLACS137_ISO002)

LN_INVPICO1_PLACS137_ISO002 = np.log(INVPICO1_PLACS137_ISO002)
print(LN_INVPICO1_PLACS137_ISO002)

LN_PICO1_PLACS137_ISO008 = np.log(PICO1_PLACS137_ISO008)
print(LN_PICO1_PLACS137_ISO008)

LN_INVPICO1_PLACS137_ISO008 = np.log(INVPICO1_PLACS137_ISO008)
print(LN_INVPICO1_PLACS137_ISO008)

LN_PICO1_PLACS137_ISO014 = np.log(PICO1_PLACS137_ISO014)
print(LN_PICO1_PLACS137_ISO014)

LN_INVPICO1_PLACS137_ISO014 = np.log(INVPICO1_PLACS137_ISO014)
print(LN_INVPICO1_PLACS137_ISO014)

-0.04908773893728771
0.04908773893728773
-0.07504677810738386
0.07504677810738393
-0.18012225136322318
0.18012225136322313


In [39]:
# lN (I/I0): AM-241 (ISOTROPICO)

#ln_ISOyAM_00595 = [LN_PICOISO_PLAAM002_00595, LN_PICOISO_PLAAM008_00595, LN_PICOISO_PLAAM014_00595]
#print(ln_ISOyAM_00595)

LN_PICO1_PLAAM241_ISO002 = np.log(PICO1_PLAAM241_ISO002)
print(LN_PICO1_PLAAM241_ISO002)

LN_INVPICO1_PLAAM241_ISO002 = np.log(INVPICO1_PLAAM241_ISO002)
print(LN_INVPICO1_PLAAM241_ISO002)

LN_PICO1_PLAAM241_ISO008 = np.log(PICO1_PLAAM241_ISO008)
print(LN_PICO1_PLAAM241_ISO008)

LN_INVPICO1_PLAAM241_ISO008 = np.log(INVPICO1_PLAAM241_ISO008)
print(LN_INVPICO1_PLAAM241_ISO008)

LN_PICO1_PLAAM241_ISO014 = np.log(PICO1_PLAAM241_ISO014)
print(LN_PICO1_PLAAM241_ISO014)

LN_INVPICO1_PLAAM241_ISO014 = np.log(INVPICO1_PLAAM241_ISO014)
print(LN_INVPICO1_PLAAM241_ISO014)

-0.05856915500990832
0.05856915500990833
-0.17804212924351606
0.1780421292435161
-0.2952789689526551
0.2952789689526552


In [41]:
# CS 137 - EXPERIMENTAL
 
# LOGARITMO NATURAL - np.log(I/I0)

ln_yCS137_EXP0662 = [LN_PICO1_PLACS137_EXP002, LN_PICO1_PLACS137_EXP008, LN_PICO1_PLACS137_EXP014]
print(ln_yCS137_EXP0662)

#LOGARITMO NATURAL INVERSO - np.log(I0/I)

ln_INVyCS137_EXP0662 = [LN_INVPICO1_PLACS137_EXP002, LN_INVPICO1_PLACS137_EXP008, LN_INVPICO1_PLACS137_EXP014]
print(ln_INVyCS137_EXP0662)

[0.0032736710159329665, -0.09397829795463669, -0.13925963571960903]
[-0.0032736710159328806, 0.09397829795463669, 0.13925963571960898]


In [42]:
# AM-241 - EXPERIMENTAL

# LOGARITMO NATURAL - np.log(I/I0)

ln_yAM241_EXP00595 = [LN_PICO1_PLAAM241_EXP002, LN_PICO1_PLAAM241_EXP008, LN_PICO1_PLAAM241_EXP014]
print(ln_yAM241_EXP00595)

#LOGARITMO NATURAL INVERSO - np.log(I0/I)

ln_INVyAM241_EXP00595 = [LN_INVPICO1_PLAAM241_EXP002, LN_INVPICO1_PLAAM241_EXP008, LN_INVPICO1_PLAAM241_EXP014]
print(ln_INVyAM241_EXP00595)

[-0.08060403241462938, -0.00337268447863923, -0.9752332675076051]
[0.08060403241462935, 0.003372684478639156, 0.9752332675076051]


In [43]:
# CS 137 - PENCIL BEAM
 

# LOGARITMO NATURAL - np.log(I/I0)

ln_yCS137_PBEAM0662 = [LN_PICO1_PLACS137_PBEAM002, LN_PICO1_PLACS137_PBEAM008, LN_PICO1_PLACS137_PBEAM014]
print(ln_yCS137_PBEAM0662)

#LOGARITMO NATURAL INVERSO - np.log(I0/I)

ln_INVyCS137_PBEAM0662 = [LN_INVPICO1_PLACS137_PBEAM002, LN_INVPICO1_PLACS137_PBEAM008, LN_INVPICO1_PLACS137_PBEAM014]
print(ln_INVyCS137_PBEAM0662)

[-0.020636934987259024, -0.08935677381232765, -0.1567035211343791]
[0.04908773893728773, 0.07504677810738393, 0.18012225136322313]


In [50]:
# AM-241 - PENCIL BEAM

# LOGARITMO NATURAL - np.log(I/I0)

ln_yAM241_00595 = [LN_PICO1_PLAAM241_PBEAM002, LN_PICO1_PLAAM241_PBEAM008, LN_PICO1_PLAAM241_PBEAM014]
print(ln_yAM241_00595)

#LOGARITMO NATURAL INVERSO - np.log(I0/I)

ln_INVyAM241_00595 = [LN_INVPICO1_PLAAM241_PBEAM002, LN_INVPICO1_PLAAM241_PBEAM008, LN_INVPICO1_PLAAM241_PBEAM014]
print(ln_INVyAM241_00595)

[-0.05231155432318328, -0.20971258664407325, -0.36750330018330973]
[0.05231155432318324, 0.20971258664407322, 0.3675033001833097]


In [52]:
# CS 137 - ISOTRÓPICO
 

# LOGARITMO NATURAL - np.log(I/I0)

ln_yCS137_ISO0662 = [LN_PICO1_PLACS137_ISO002, LN_PICO1_PLACS137_ISO008, LN_PICO1_PLACS137_ISO014]
print(ln_yCS137_ISO0662)

#LOGARITMO NATURAL INVERSO - np.log(I0/I)

ln_INVyCS137_ISO0662 = [LN_INVPICO1_PLACS137_ISO002, LN_INVPICO1_PLACS137_ISO008, LN_INVPICO1_PLACS137_ISO014]
print(ln_INVyCS137_ISO0662)

[-0.04908773893728771, -0.07504677810738386, -0.18012225136322318]
[0.04908773893728773, 0.07504677810738393, 0.18012225136322313]


In [53]:
# AM-241 - ISOTRÓPICO

# LOGARITMO NATURAL - np.log(I/I0)

ln_yAM241_00595 = [LN_PICO1_PLAAM241_ISO002, LN_PICO1_PLAAM241_ISO008, LN_PICO1_PLAAM241_ISO014]
print(ln_yAM241_00595)

#LOGARITMO NATURAL INVERSO - np.log(I0/I)

ln_INVyAM241_ISO00595 = [LN_INVPICO1_PLAAM241_ISO002, LN_INVPICO1_PLAAM241_ISO008, LN_INVPICO1_PLAAM241_ISO014]
print(ln_INVyAM241_ISO00595)


[-0.05856915500990832, -0.17804212924351606, -0.2952789689526551]
[0.05856915500990833, 0.1780421292435161, 0.2952789689526552]


In [ ]:
################################################################################################################################
################################################################################################################################
################################################################################################################################
################################################################################################################################
################################################################################################################################
################################################################################################################################
################################################################################################################################
################################################################################################################################
################################################################################################################################
################################################################################################################################
################################################################################################################################
################################################################################################################################
################################################################################################################################



In [36]:
# I/I0 - VALOR NORMAL (CS137 - EXPERIMENTAL) (PICO 1 - 662 KEV)

################################################################################################################################

# x1 = np.array([0.2, 0.8, 1.4])
# y1 = np.array([1.0032790353289613, 0.9966329966329966, 0.8700021155066638])

################################################################################################################################


# COEF A

# a1= -0.11106409985191462

# COEF B

# b1= 1.045489329037739

# ERRO

# erro_a1 = 0.04713449762339604

# erro_b1 = 0.04421607809682735

In [37]:
# LN(I/I0) EXP - VALOR NORMAL (CS137 - EXP) (PICO 1 - 662 KEV)

################################################################################################################################

# x2 = np.array([0.2, 0.8, 1.4])
# y2 = np.array([0.9225589225589226, 0.9966329966329966, 0.3771043771043771])

################################################################################################################################


# COEF A

a2=-0.45454545454545464

# COEF B

b2=1.1290684624017957

# ERRO

erro_a2 = 0.2724728711642889

erro_b2 = 0.2556022098066639

In [ ]:
# ERRO

# QUADRÁTICA EXP - VALOR NORMAL (CS137 - EXP) (PICO 1 - 662 KEV)

################################################################################################################################

# [0 0 0]

################################################################################################################################


# COEF A

# a3 = -0.45454545454545464

# COEF B

# b3 = 1.1290684624017957

# ERRO

# erro_a3 = 

# erro_b3 = 

In [38]:
# CONTAGEM EXP - VALOR NORMAL (CS137 - EXP) (PICO 1 - 662 KEV)

################################################################################################################################

# x2 = np.array([0.2, 0.8, 1.4])
# y2 = np.array([9485, 8606, 8225])

################################################################################################################################


# COEF A

a4 = -1050.0000000000002

# COEF B

b4 = 9612.0

# ERRO

erro_a4 = 195.6328761282782

erro_b4 = 183.51990506633217

In [ ]:
# ERRO

# EXPONENCIAL EXP - VALOR NORMAL (CS137 - EXP) (PICO 1 - 662 KEV)

################################################################################################################################

# [0 0 0] 

################################################################################################################################


# COEF A

a1=

# COEF B

b1=

# ERRO

erro_a1 = 

erro_b1 = 

In [ ]:
# (I/I0) EXP - VALOR INVERSO (CS137 - EXP) (PICO 1 - 662 KEV)

################################################################################################################################


# [0 0 0]


################################################################################################################################


# COEF A

a2=

# COEF B

b2=

# ERRO

erro_a2= 

erro_b2= 


In [ ]:
# LN(I/I0) EXP - VALOR INVERSO (CS137 - EXP) (PICO 1 - 662 KEV)

################################################################################################################################


# [-0.00327367  0.0939783   0.13925964]


################################################################################################################################


# COEF A

a2=0.11877775833333334

# COEF B

b2=-0.018367450000000007

# ERRO

erro_a2= 0.020415991608631685

erro_b2= 0.019151897758709787


In [ ]:
# ERRO

# QUADRÁTICA EXP - VALOR INVERSO (CS137 - EXP) (PICO 1 - 662 KEV)

################################################################################################################################

# [0.00327367 -0.0939783  -0.13925964] 

################################################################################################################################


# COEF A

a1=

# COEF B

b1=

# ERRO

erro_a1 = 

erro_b1 = 

In [ ]:
# CONTAGEM EXP - VALOR INVERSO (CS137 - EXP) (PICO 1 - 662 KEV)

################################################################################################################################


# [0 0 0]


################################################################################################################################


# COEF A

a2=

# COEF B

b2=

# ERRO

erro_a2= 

erro_b2= 


In [ ]:
# ERRO

# EXPONENCIAL EXP - VALOR INVERSO (CS137 - EXP) (PICO 1 - 662 KEV)

################################################################################################################################


# [0 0 0]


################################################################################################################################


# COEF A

a2=

# COEF B

b2=

# ERRO

erro_a2= 

erro_b2= 


In [ ]:
# (I/I0) EXP - VALOR NORMAL (AM241 - EXP) (PICO 1 - 59.5 KEV)

################################################################################################################################

# [0 0 0] 

################################################################################################################################


# COEF A

a1=-0.11877775833333334

# COEF B

b1=0.018367450000000007

# ERRO

erro_a1 = 0.021216920851829954

erro_b1 = 0.02598531500000004

In [ ]:
# LN(I/I0) EXP - VALOR NORMAL (AM241 - EXP) (PICO 1 - 59.5 KEV)

################################################################################################################################

# [0.00327367 -0.0939783  -0.13925964] 

################################################################################################################################


# COEF A

a1=-0.11877775833333334

# COEF B

b1=0.018367450000000007

# ERRO

erro_a1 = 0.021216920851829954

erro_b1 = 0.02598531500000004

In [ ]:
# LN(I/I0) EXP - VALOR NORMAL (AM241 - EXP) (PICO 1 - 59.5 KEV)

################################################################################################################################

# [0.00327367 -0.0939783  -0.13925964] 

################################################################################################################################


# COEF A

a1=-0.11877775833333334

# COEF B

b1=0.018367450000000007

# ERRO

erro_a1 = 0.021216920851829954

erro_b1 = 0.02598531500000004

In [ ]:
# LN(I/I0) EXP - VALOR NORMAL (AM241 - EXP) (PICO 1 - 59.5 KEV)

################################################################################################################################

# [0.00327367 -0.0939783  -0.13925964] 

################################################################################################################################


# COEF A

a1=-0.11877775833333334

# COEF B

b1=0.018367450000000007

# ERRO

erro_a1 = 0.021216920851829954

erro_b1 = 0.02598531500000004

In [ ]:
# LN(I/I0) EXP - VALOR NORMAL (AM241 - EXP) (PICO 1 - 59.5 KEV)

################################################################################################################################

# [0.00327367 -0.0939783  -0.13925964] 

################################################################################################################################


# COEF A

a1=-0.11877775833333334

# COEF B

b1=0.018367450000000007

# ERRO

erro_a1 = 0.021216920851829954

erro_b1 = 0.02598531500000004

In [ ]:
# LN(I/I0) EXP - VALOR INVERSO (AM241 - EXP) (PICO 1 - 59.5 KEV)

################################################################################################################################

# [0.00327367 -0.0939783  -0.13925964] 

################################################################################################################################


# COEF A

a1=-0.11877775833333334

# COEF B

b1=0.018367450000000007

# ERRO

erro_a1 = 0.021216920851829954

erro_b1 = 0.02598531500000004

In [21]:
X_002 = 0.2
X_008 = 0.8
X_014 = 1.4

In [23]:
# I/I0 EXP - VALOR 1 (CS137 - EXP) (PICO 1 - 662 KEV)

# EQUAÇÃO E COEF PEARSON - CALCULO ESPESSURA #

################################################################################################################################

"EQUAÇÃO LINEAR"

################################################################################################################################

# R**2 = 0.9505

Y1_EXP_CS002=-0.1111*X_002+1.0167
print(Y1_EXP_CS002)
Y1_EXP_CS008=-0.1111*X_008+1.0167
print(Y1_EXP_CS008)
Y1_EXP_CS014=-0.1111*X_014+1.0167
print(Y1_EXP_CS014)

# R**2 = 0.9505

#Y1_EXP_CS002=-0.1111*PICO1_PLACS002_0662+1.0167
#print(Y1_EXP_CS002)
#Y1_EXP_CS008=-0.1111*PICO1_PLACS008_0662+1.0167
#print(Y1_EXP_CS008)
#Y1_EXP_CS014=-0.1111*PICO1_PLACS014_0662+1.0167
#print(Y1_EXP_CS014)

X1_EXP_CS002=np.abs((PICO1_PLACS137_EXP002-1.0167)/-0.1111)
print(f'equação linear - espessura 0.2 mm:{X1_EXP_CS002}')
X1_EXP_CS008=np.abs((PICO1_PLACS137_EXP008-1.0167)/-0.1111)
print(f'equação linear - espessura 0.8 mm:{X1_EXP_CS008}')
X1_EXP_CS014=np.abs((PICO1_PLACS137_EXP014-1.0167)/-0.1111)
print(f'equação linear - espessura 1.4 mm:{X1_EXP_CS014}')

################################################################################################################################

"EQUAÇÃO LOGARITMICA"

################################################################################################################################


# R**2 = 0.9997

Y2_EXP_CS002=-0.068*np.log(X_002)+0.8938
print(Y2_EXP_CS002)
Y2_EXP_CS008=-0.068*np.log(X_008)+0.8938
print(Y2_EXP_CS008)
Y2_EXP_CS014=-0.068*np.log(X_014)+0.8938
print(Y2_EXP_CS014)

# NÃO TEM VALOR PRA ESSA EQUAÇÃO #

################################################################################################################################

"EQUAÇÃO QUADRÁTICA"

################################################################################################################################

# R**2 = 1

Y3_EXP_CS002 = 0.0732*X_002**2-0.2281*X_002+1.046
print(Y3_EXP_CS002)
Y3_EXP_CS008 = 0.0732*X_008**2-0.2281*X_008+1.046
print(Y3_EXP_CS008)
Y3_EXP_CS014 = 0.0732*X_014**2-0.2281*X_014+1.046
print(Y3_EXP_CS014)

x3_EXP_CS1 = 1.5580601092896174
print(f'equação quadrática - primeira raiz:{x3_EXP_CS1}')
x3_EXP_CS2 = 0
print(f'equação quadrática - segunda raiz:{x3_EXP_CS2}')

################################################################################################################################

"EQUAÇÃO EXPONENCIAL"

################################################################################################################################

# R**2 = 0.9576

Y4_EXP_CS002=1.0185*np.exp(-0.119*X_002)
print(Y4_EXP_CS002)
Y4_EXP_CS008=1.0185*np.exp(-0.119*X_008)
print(Y4_EXP_CS008)
Y4_EXP_CS014=1.0185*np.exp(-0.119*X_014)
print(Y4_EXP_CS014)

X4_EXP_CS002=np.log(PICO1_PLACS137_EXP002/1.0185)/(-0.119)
print(f'equação exponencial - espessura 0.2 mm:{X4_EXP_CS002}')
X4_EXP_CS008=np.log(PICO1_PLACS137_EXP008/1.0185)/(-0.119)
print(f'equação exponencial - espessura 0.8 mm:{X4_EXP_CS008}')
X4_EXP_CS014=np.log(PICO1_PLACS137_EXP014/1.0185)/(-0.119)
print(f'equação exponencial - espessura 1.4 mm:{X4_EXP_CS014}')

# NÃO TEM VALOR PRA ESSA EQUAÇÃO #

0.9944799999999999
0.9278199999999999
0.8611599999999999
equação linear - espessura 0.2 mm:0.12080076211555889
equação linear - espessura 0.8 mm:0.9576731102346528
equação linear - espessura 1.4 mm:1.320413001740199
1.003241778045519
0.9089737614893663
0.8709198879097576
1.003308
0.9103680000000001
0.8701320000000001
equação quadrática - primeira raiz:1.5580601092896174
equação quadrática - segunda raiz:0
0.9945458846757741
0.9260111130118343
0.8621991148261234
equação exponencial - espessura 0.2 mm:0.12653181234277716
equação exponencial - espessura 0.8 mm:0.9437752490702533
equação exponencial - espessura 1.4 mm:1.3242906924733824


In [24]:
# LN (I/I0) EXP - VALOR 1 (CS137 - EXP) (PICO 1 - 662 KEV)

# EQUAÇÃO E COEF PEARSON - CALCULO ESPESSURA #

################################################################################################################################

"EQUAÇÃO LINEAR"

################################################################################################################################


# R**2 = 0.9576

YY1_EXP_CS002=-0.1188*X_002+0.0184
print(YY1_EXP_CS002)
YY1_EXP_CS008=-0.1188*X_008+0.0184
print(YY1_EXP_CS008)
YY1_EXP_CS014=-0.1188*X_014+0.0184
print(YY1_EXP_CS014)

XX1_EXP_CS002 = np.abs((np.log(PICO1_PLACS137_EXP002)-0.0184)/(-0.1188))
print(f'equação linear - espessura 0.2 mm:{XX1_EXP_CS002}')
XX1_EXP_CS008 = np.abs((np.log(PICO1_PLACS137_EXP008)-0.0184)/(-0.1188))
print(f'equação linear - espessura 0.8 mm:{XX1_EXP_CS008}')
XX1_EXP_CS014 = np.abs((np.log(PICO1_PLACS137_EXP014)-0.0184)/(-0.1188))
print(f'equação linear - espessura 1.4 mm:{XX1_EXP_CS014}')

################################################################################################################################

"EQUAÇÃO LOGARITMICA"

################################################################################################################################


# R**2 = 0.9989

YY2_EXP_CS002=-0.073*np.log(X_002)-0.1129
print(YY2_EXP_CS002)
YY2_EXP_CS008=-0.073*np.log(X_008)-0.1129
print(YY2_EXP_CS008)
YY2_EXP_CS014=-0.073*np.log(X_014)-0.1129
print(YY2_EXP_CS014)

# NÃO TEM VALOR PRA ESSA EQUAÇÃO #

################################################################################################################################

"EQUAÇÃO QUADRÁTICA"

################################################################################################################################


# R**2 = 1

YY3_EXP_CS002 = 0.0722*X_002**2-0.2343*X_002+0.0472
print(YY3_EXP_CS002)
YY3_EXP_CS008 = 0.0722*X_008**2-0.2343*X_008+0.0472
print(YY3_EXP_CS008)
YY3_EXP_CS014 = 0.0722*X_014**2-0.2343*X_014+0.0472
print(YY3_EXP_CS014)

xx3_EXP_CS1 = 3.029350444502868
print(f'equação quadrática - primeira raiz:{xx3_EXP_CS1}')
xx3_EXP_CS2 = 0.21580191006776953
print(f'equação quadrática - segunda raiz:{xx3_EXP_CS2}')

################################################################################################################################

"EQUAÇÃO EXPONENCIAL"

################################################################################################################################


# NÃO TEM VALOR PRA ESSA EQUAÇÃO #


-0.005360000000000004
-0.07664000000000001
-0.14792
equação linear - espessura 0.2 mm:0.1273260015493858
equação linear - espessura 0.8 mm:0.9459452689784233
equação linear - espessura 1.4 mm:1.3271013107711198
0.004588967607689315
-0.09661052075406269
-0.13746247327334854
0.0032279999999999948
-0.09403200000000003
-0.13930800000000002
equação quadrática - primeira raiz:3.029350444502868
equação quadrática - segunda raiz:0.21580191006776953


'EQUAÇÃO EXPONENCIAL'

In [25]:
# CONTAGEM EXP - VALOR 1 (CS137 - EXP) (PICO 1 - 662 KEV)

# EQUAÇÃO E COEF PEARSON - CALCULO ESPESSURA #

################################################################################################################################

"EQUAÇÃO LINEAR"

################################################################################################################################


# R**2 = 0.9505

YYY01_EXP_CS002=-1050*X_002+9612
print(YYY01_EXP_CS002)
YYY01_EXP_CS008=-1050*X_008+9612
print(YYY01_EXP_CS008)
YYY01_EXP_CS014=-1050*X_014+9612
print(YYY01_EXP_CS014)

XXX1_EXP_CS002=np.abs((CONTEXP002_CS137_0662-9612)/-1050)
print(f'equação linear - espessura 0.2 mm:{XXX1_EXP_CS002}')
XXX1_EXP_CS008=np.abs((CONTEXP008_CS137_0662-9612)/-1050)
print(f'equação linear - espessura 0.8 mm:{XXX1_EXP_CS008}')
XXX1_EXP_CS014=np.abs((CONTEXP014_CS137_0662-9612)/-1050)
print(f'equação linear - espessura 1.4 mm:{XXX1_EXP_CS014}')

################################################################################################################################

"EQUAÇÃO LOGARITMICA"

################################################################################################################################


# R**2 = 0.9997

YYY2_EXP_CS002=-645*np.log(X_002)+8450.4
print(YYY2_EXP_CS002)
YYY2_EXP_CS008=-645*np.log(X_008)+8450.4
print(YYY2_EXP_CS008)
YYY2_EXP_CS014=-645*np.log(X_014)+8450.4
print(YYY2_EXP_CS014)

# NÃO TEM VALOR PRA ESSA EQUAÇÃO #

################################################################################################################################

"EQUAÇÃO QUADRÁTICA"

################################################################################################################################


# R**2 = 1

YYY3_EXP_CS002 = 691.67*X_002**2-2156.7*X_002+9888.7
print(YYY3_EXP_CS002)
YYY3_EXP_CS008 = 691.67*X_002**2-2156.7*X_008+9888.7
print(YYY3_EXP_CS008)
YYY3_EXP_CS014 =691.67*X_002**2-2156.7*X_014+9888.7
print(YYY3_EXP_CS014)

xx3_EXP_CS1 = 1.5590527274567352
print(f'equação quadrática - primeira raiz:{xx3_EXP_CS1}')
xx3_EXP_CS2 = 0
print(f'equação quadrática - segunda raiz:{xx3_EXP_CS2}')

################################################################################################################################


"EQUAÇÃO EXPONENCIAL"

################################################################################################################################


YYY4_EXP_CS002=9629*np.exp(-0.119*X_002)
print(YYY4_EXP_CS002)
YYY4_EXP_CS008=9629*np.exp(-0.119*X_008)
print(YYY4_EXP_CS008)
YYY4_EXP_CS014=9629*np.exp(-0.119*X_014)
print(YYY4_EXP_CS014)

XXX4_EXP_CS002=np.abs(np.log(CONTEXP002_CS137_0662/9629)/-0.119)
print(f'equação exponencial - espessura 0.2 mm:{XXX4_EXP_CS002}')
XXX4_EXP_CS008=np.abs(np.log(CONTEXP008_CS137_0662/9629)/-0.119)
print(f'equação exponencial - espessura 0.8 mm:{XXX4_EXP_CS008}')
XXX4_EXP_CS014=np.abs(np.log(CONTEXP014_CS137_0662/9629)/-0.119)
print(f'equação exponencial - espessura 1.4 mm:{XXX4_EXP_CS014}')


# NÃO TEM VALOR PRA ESSA EQUAÇÃO #


9402.0
8772.0
8142.0
equação linear - espessura 0.2 mm:0.12095238095238095
equação linear - espessura 0.8 mm:0.9580952380952381
equação linear - espessura 1.4 mm:1.3209523809523809
9488.487453519994
8594.327590597664
8233.375407379317
9485.026800000001
8191.006800000001
6896.986800000001
equação quadrática - primeira raiz:1.5590527274567352
equação quadrática - segunda raiz:0
9402.535418304396
8754.600890712767
8151.315931920219
equação exponencial - espessura 0.2 mm:0.12661995690058278
equação exponencial - espessura 0.8 mm:0.9438633936280592
equação exponencial - espessura 1.4 mm:1.324378837031187


In [27]:
# [(I/I0) - (inverso)] EXP - VALOR 1 (CS137 - EXP) (PICO 1 - 662 KEV)

# EQUAÇÃO E COEF PEARSON - CALCULO ESPESSURA #

################################################################################################################################

"EQUAÇÃO LINEAR"

################################################################################################################################


# R**2 = 0.9643

YINV01_EXP_CS002=0.1272*X_002+0.9798
print(YINV01_EXP_CS002)
YINV01_EXP_CS008=0.1272*X_008+0.9798
print(YINV01_EXP_CS008)
YINV01_EXP_CS014=0.1272*X_014+0.9798
print(YINV01_EXP_CS014)

XINV1_EXP_CS002=np.abs((PICO1_PLACS137_EXP002-0.9798)/0.1272)
print(f'equação linear - espessura 0.2 mm:{XINV1_EXP_CS002}')
XINV1_EXP_CS008=np.abs((PICO1_PLACS137_EXP008-0.9798)/0.1272)
print(f'equação linear - espessura 0.8 mm:{XINV1_EXP_CS008}')
XINV1_EXP_CS014=np.abs((PICO1_PLACS137_EXP014-0.9798)/0.1272)
print(f'equação linear - espessura 1.4 mm:{XINV1_EXP_CS014}')

################################################################################################################################

"EQUAÇÃO LOGARITMICA"

################################################################################################################################


# R**2 = 0.9975

YYINV2_EXP_CS002=0.0775*np.log(X_002)+1.1202
print(YYINV2_EXP_CS002)
YYINV2_EXP_CS008=0.0775*np.log(X_008)+1.1202
print(YYINV2_EXP_CS008)
YYINV2_EXP_CS014=0.0775*np.log(X_014)+1.1202
print(YYINV2_EXP_CS014)

# NÃO TEM VALOR PRA ESSA EQUAÇÃO #

################################################################################################################################

"EQUAÇÃO QUADRÁTICA"

################################################################################################################################


# R**2 = 1

YINV3_EXP_CS002 = -0.0707*X_002**2+0.2404*X_002+0.9515
print(YINV3_EXP_CS002)
YINV3_EXP_CS008 = -0.0707*X_008**2+0.2404*X_008+0.9515
print(YINV3_EXP_CS008)
YINV3_EXP_CS014 = -0.0707*X_014**2+0.2404*X_002+0.9515
print(YINV3_EXP_CS014)

xx3_EXP_CS1 = -2.3432179679857383
print(f'equação quadrática - primeira raiz:{xx3_EXP_CS1}')
xx3_EXP_CS2 = 5.743500853417138
print(f'equação quadrática - segunda raiz:{xx3_EXP_CS2}')

################################################################################################################################


"EQUAÇÃO EXPONENCIAL"

################################################################################################################################


# R**2 = 0.9576


YYINV2_EXP_CS002=0.9818*np.exp(0.1188*X_002)
print(YYINV2_EXP_CS002)
YYINV2_EXP_CS008=0.9818*np.exp(0.1188*X_008)
print(YYINV2_EXP_CS008)
YYINV2_EXP_CS014=0.9818*np.exp(0.1188*X_014)
print(YYINV2_EXP_CS014)


# NÃO TEM VALOR PRA ESSA EQUAÇÃO #


1.00524
1.08156
1.15788
equação linear - espessura 0.2 mm:0.18458361107674007
equação linear - espessura 0.8 mm:0.5463638565021226
equação linear - espessura 1.4 mm:0.8631909158281145
0.9954685617863573
1.102906374773149
1.146276598338144
0.996752
1.098572
0.861008
equação quadrática - primeira raiz:-2.3432179679857383
equação quadrática - segunda raiz:5.743500853417138
1.0054069074891794
1.079688250629094
1.1594576383582877


In [28]:
# [ln(I/I0) - (inverso)] EXP - VALOR 1 (CS137 - EXP) (PICO 1 - 662 KEV)

# EQUAÇÃO E COEF PEARSON - CALCULO ESPESSURA #

################################################################################################################################

"EQUAÇÃO LINEAR"

################################################################################################################################


# R**2 = 0.9576

YYINV1_EXP_CS002=0.1188*X_002-0.0184
print(YYINV1_EXP_CS002)
YYINV1_EXP_CS008=0.1188*X_008-0.0184
print(YYINV1_EXP_CS008)
YYINV1_EXP_CS014=0.1188*X_014-0.0184
print(YYINV1_EXP_CS014)

XXINV1_EXP_CS002 = np.abs((np.log(PICO1_PLACS137_EXP002)+0.0184)/(0.1188))
print(f'equação linear - espessura 0.2 mm:{XXINV1_EXP_CS002}')
XXINV1_EXP_CS008 = np.abs((np.log(PICO1_PLACS137_EXP008)+0.0184)/(0.1188))
print(f'equação linear - espessura 0.2 mm:{XXINV1_EXP_CS008}')
XXINV1_EXP_CS014 = np.abs((np.log(PICO1_PLACS137_EXP014)+0.0184)/(0.1188))
print(f'equação linear - espessura 0.2 mm:{XXINV1_EXP_CS014}')

XXINV01_EXP_CS002=np.abs((PICO1_PLACS137_EXP002-0.9798)/0.1272)
print(f'equação linear - espessura 0.2 mm:{XXINV01_EXP_CS002}')
XXINV01_EXP_CS008=np.abs((PICO1_PLACS137_EXP008-0.9798)/0.1272)
print(f'equação linear - espessura 0.8 mm:{XXINV01_EXP_CS008}')
XXINV01_EXP_CS014=np.abs((PICO1_PLACS137_EXP014-0.9798)/0.1272)
print(f'equação linear - espessura 1.4 mm:{XXINV01_EXP_CS014}')

################################################################################################################################

"EQUAÇÃO LOGARITMICA"

################################################################################################################################


# R**2 = 0.9989

YYINV2_EXP_CS002=0.0727*np.log(X_002)+0.1129
print(YYINV2_EXP_CS002)
YYINV2_EXP_CS008=0.0727*np.log(X_008)+0.1129
print(YYINV2_EXP_CS008)
YYINV2_EXP_CS014=0.0727*np.log(X_014)+0.1129
print(YYINV2_EXP_CS014)

# NÃO TEM VALOR PRA ESSA EQUAÇÃO #

################################################################################################################################

"EQUAÇÃO QUADRÁTICA"

################################################################################################################################


# R**2 = 1

YYINV3_EXP_CS002 = -0.0722*X_002**2+0.2343*X_002-0.0472
print(YYINV3_EXP_CS002)
YYINV3_EXP_CS008 = -0.0722*X_008**2+0.2343*X_008-0.0472
print(YYINV3_EXP_CS008)
YYINV3_EXP_CS014 = -0.0722*X_014**2+0.2343*X_014-0.0472
print(YYINV3_EXP_CS014)

xx3_EXP_CS1 = -2.3432179679857383
print(f'equação quadrática - primeira raiz:{xx3_EXP_CS1}')
xx3_EXP_CS2 = 3.029350444502868
print(f'equação quadrática - segunda raiz:{xx3_EXP_CS2}')

################################################################################################################################


"EQUAÇÃO EXPONENCIAL"

################################################################################################################################



# NÃO TEM VALOR PRA ESSA EQUAÇÃO #


0.005360000000000004
0.07664000000000001
0.14792
equação linear - espessura 0.2 mm:0.18243830821492393
equação linear - espessura 0.2 mm:0.6361809592141136
equação linear - espessura 0.2 mm:1.01733700100681
equação linear - espessura 0.2 mm:0.18458361107674007
equação linear - espessura 0.8 mm:0.5463638565021226
equação linear - espessura 1.4 mm:0.8631909158281145
-0.0041061362339590846
0.09667746381945695
0.13736153160236217
-0.0032279999999999948
0.09403200000000003
0.13930800000000002
equação quadrática - primeira raiz:-2.3432179679857383
equação quadrática - segunda raiz:3.029350444502868


'EQUAÇÃO EXPONENCIAL'

In [71]:
# I/I0 EXP - VALOR 1 (AM241 - EXP) (PICO 1 - 59.5 KEV)

# EQUAÇÃO E COEF PEARSON - CALCULO ESPESSURA #

################################################################################################################################

"EQUAÇÃO LINEAR"

################################################################################################################################

# R**2 = 0.6498

# Y1_EXP_AM002=-0.4545*X_002+1.1291
# print(Y1_EXP_AM002)
# Y1_EXP_PBEAM_AM008=-0.4545*X_008+1.1291
# print(Y1_EXP_AM008)
# Y1_EXP_AM014=-0.4545*X_014+1.1291
# print(Y1_EXP_AM014)

X1_EXP_AM002=np.abs((PICOEXP_PLAAM002_00595-1.1291)/-0.4545)
print(f'equação linear - espessura 0.2 mm: {X1_EXP_AM002}')
X1_EXP_AM008=np.abs((PICOEXP_PLAAM008_00595-1.1291)/-0.4545)
print(f'equação linear - espessura 0.8 mm: {X1_EXP_AM008}')
X1_EXP_AM014=np.abs((PICOEXP_PLAAM014_00595-1.1291)/-0.4545)
print(f'equação linear - espessura 1.4 mm: {X1_EXP_AM014}')


################################################################################################################################

"EQUAÇÃO LOGARITMICA"

################################################################################################################################

# R**2 = 0.412

# Y2_EXP_AM002=-0.217*np.log(X_002)+0.6573
# print(Y2_EXP_AM002)
# Y2_EXP_AM008=-0.217*np.log(X_008)+0.6573
# print(Y2_EXP_AM008)
# Y2_EXP_AM014=-0.217*np.log(X_014)+0.6573
# print(Y2_EXP_AM014)

################################################################################################################################

"EQUAÇÃO QUADRÁTICA"

################################################################################################################################

# R**2 = 1

#Y3_EXP_AM002 = -0.9633*X_002**2+1.0868*X_002+0.7437
#print(Y3_EXP_AM002)
#Y3_EXP_AM008 = -0.9633*X_002**2+1.0868*X_008+0.7437
#print(Y3_EXP_AM008)
#Y3_EXP_AM014 = -0.9633*X_002**2+1.0868*X_014+0.7437
#print(Y3_EXP_AM014)

x3_EXP_AM1 = -0.4800455753914926
print(f'equação quadrática - primeira raiz:{x3_EXP_AM1}')
x3_EXP_AM2 = 1.6082507035966
print(f'equação quadrática - segunda raiz:{x3_EXP_AM2}')

################################################################################################################################

"EQUAÇÃO EXPONENCIAL"

################################################################################################################################


# R**2 = 0.6857

#Y4_EXP_AM002=1.2755*np.exp(-0.746*X_002)
#print(Y4_EXP_AM002)
#Y4_EXP_AM008=1.2755*np.exp(-0.746*X_008)
#print(Y4_EXP_AM008)
#Y4_EXP_AM014=1.2755*np.exp(-0.746*X_014)
#print(Y4_EXP_AM014)

X4_EXP_AM002=(np.log(PICOEXP_PLAAM002_00595/1.2755)/(-0.746))
print(f'equação exponencial - espessura 0.2 mm:{X4_EXP_AM002}')
X4_EXP_AM008=(np.log(PICOEXP_PLAAM008_00595/1.2755)/(-0.746))
print(f'equação exponencial - espessura 0.8 mm:{X4_EXP_AM008}')
X4_EXP_AM014=(np.log(PICOEXP_PLAAM014_00595/1.2755)/(-0.746))
print(f'equação exponencial - espessura 1.4 mm:{X4_EXP_AM014}')

equação linear - espessura 0.2 mm: 0.45443581395176547
equação linear - espessura 0.8 mm: 0.2914565530627136
equação linear - espessura 1.4 mm: 1.6545558259529654
equação quadrática - primeira raiz:-0.4800455753914926
equação quadrática - segunda raiz:1.6082507035966
equação exponencial - espessura 0.2 mm:0.43423899599779964
equação exponencial - espessura 0.2 mm:0.3307117199441934
equação exponencial - espessura 0.2 mm:1.633473895586239


In [28]:
# ln(I/I0) EXP - VALOR 1 (AM241 - EXP) (PICO 1 - 59.5 KEV)

# EQUAÇÃO E COEF PEARSON - CALCULO ESPESSURA #

################################################################################################################################

"EQUAÇÃO LINEAR"

################################################################################################################################

# R**2 = 0.6857

#YY1_EXP_AM002=-0.7455*X_002+0.2433
#print(YY1_EXP_AM002)
#YY1_EXP_AM008=-0.7455*X_008+0.2433
#print(YYY1_EXP_CS008)
#YY1_EXP_AM014=-0.7455*X_014+0.2433
#print(YY1_EXP_AM014)

XX1_EXP_AM002 = np.abs((np.log(PICOEXP_PLAAM002_00595)-0.2433)/(-0.7455))
print(f'equação linear - espessura 0.2 mm:{XX1_EXP_AM002}')
XX1_EXP_AM008 = np.abs((np.log(PICOEXP_PLAAM008_00595)-0.2433)/(-0.7455))
print(f'equação linear - espessura 0.8 mm:{XX1_EXP_AM008}')
XX1_EXP_AM014 = np.abs((np.log(PICOEXP_PLAAM014_00595)-0.2433)/(-0.7455))
print(f'equação linear - espessura 1.4 mm:{XX1_EXP_AM014}')

################################################################################################################################

"EQUAÇÃO LOGARITMICA"

################################################################################################################################

# R**2 = 0.4498

# YY2_EXP_CS002=-0.362*np.log(X_002)-0.5334
# print(YY2_EXP_CS002)
# YY2_EXP_CS008=-0.362*np.log(X_008)-0.5334
# print(YY2_EXP_CS008)
# YY2_EXP_CS014=-0.362*np.log(X_014)-0.5334
# print(YY2_EXP_CS014)


################################################################################################################################

"EQUAÇÃO QUADRÁTICA"

################################################################################################################################

# R**2 = 1

#YY3_EXP_AM002 = -1.4571*X_002**2+1.5858*X_002-0.3395
#print(YY3_EXP_AM002)
#YY3_EXP_AM008 = -1.4571*X_008**2+1.5858*X_008-0.3395
#print(YY3_EXP_AM008)
#YY3_EXP_AM014 = -1.4571*X_014**2+1.5858*X_014-0.3395
#print(YY3_EXP_AM014)

xx3_EXP_AM1 = 0.29293330647485183
print(f'equação quadrática - primeira raiz:{xx3_EXP_AM1}')
xx3_EXP_AM2 = 0.7953928207641846
print(f'equação quadrática - segunda raiz:{xx3_EXP_AM2}')

################################################################################################################################

"EQUAÇÃO EXPONENCIAL"

################################################################################################################################

# NÃO TEM VALOR PRA ESSA EQUAÇÃO #


# CERTO #

equação linear - espessura 0.2 mm:0.4344789167198248
equação linear - espessura 0.8 mm:0.33088220587342615
equação linear - espessura 1.4 mm:1.634518132136291
equação quadrática - primeira raiz:0.29293330647485183
equação quadrática - segunda raiz:0.7953928207641846


'EQUAÇÃO EXPONENCIAL'

In [50]:
# CONTAGEM EXP - VALOR 1 (AM241 - EXP) (PICO 1 - 59.5 KEV)

# EQUAÇÃO E COEF PEARSON - CALCULO ESPESSURA #

################################################################################################################################

"EQUAÇÃO LINEAR"

################################################################################################################################

# R**2 = 0.6498

#YYY1_EXP_AM002=-270*X_002+670.67
#print(YY1_EXP_AM002)
#YYY1_EXP_AM008=-270*X_008+670.67
#print(YY1_EXP_AM008)
#YYY1_EXP_AM014=-270*X_014+670.67
#print(YY1_EXP_AM014)

XXX1_EXP_AM002=np.abs((CONTEXP002_AM241_00595-670.67)/-270)
print(f'equação linear - espessura 0.2 mm:{XXX1_EXP_AM002}')
XXX1_EXP_AM008=np.abs((CONTEXP008_AM241_00595-670.67)/-270)
print(f'equação linear - espessura 0.8 mm:{XXX1_EXP_AM008}')
XXX1_EXP_AM014=np.abs((CONTEXP014_AM241_00595-670.67)/-270)
print(f'equação linear - espessura 1.4 mm:{XXX1_EXP_AM014}')

################################################################################################################################

"EQUAÇÃO LOGARITMICA"

################################################################################################################################

# R**2 = 0.412

#YYY2_EXP_AM002=-128.8*np.log(X_002)+390.45
#print(YYY2_EXP_AM002)
#YYY2_EXP_AM008=-128.8*np.log(X_008)+390.45
#print(YYY2_EXP_AM008)
#YYY2_EXP_AM014=-128.8*np.log(X_014)+390.45
#print(YYY2_EXP_AM014)

# NÃO TEM VALOR PRA ESSA EQUAÇÃO #

################################################################################################################################

"EQUAÇÃO QUADRÁTICA"

################################################################################################################################

# R**2 = 1

#YYY3_EXP_AM002 = -572.22*X_002**2+645.56*X_002+441.78
#print(YYY3_EXP_AM002)
#YYY3_EXP_AM008 = -572.22*X_002**2+645.56*X_002+441.78
#print(YYY3_EXP_AM008)
#YYY3_EXP_AM014 = -572.22*X_002**2+645.56*X_002+441.78
#print(YYY3_EXP_AM014)


xxx3_EXP_AM1 = -0.48006001378122254
print(f'equação quadrática - primeira raiz:{xxx3_EXP_AM1}')
xxx3_EXP_AM2 = 1.608227501810302
print(f'equação quadrática - segunda raiz:{xxx3_EXP_AM2}')


################################################################################################################################

"EQUAÇÃO EXPONENCIAL"

################################################################################################################################

# R**2 = 0.6857

#YYY4_EXP_AM002=757.66*np.exp(-0.746*X_002)
#print(YYY4_EXP_AM002)
#YYY4_EXP_AM008=757.66*np.exp(-0.746*X_008)
#print(YYY4_EXP_AM008)
#YYY4_EXP_AM014=757.66*np.exp(-0.746*X_014)
#print(YYY4_EXP_AM014)

XXX4_EXP_AM002=np.abs(np.log(CONTEXP002_AM241_00595/757.66)/-0.746)
print(f'equação exponencial - espessura 0.2 mm:{XXX4_EXP_AM002}')
XXX4_EXP_AM008=np.abs(np.log(CONTEXP008_AM241_00595/757.66)/-0.746)
print(f'equação exponencial - espessura 0.8 mm:{XXX4_EXP_AM008}')
XXX4_EXP_AM014=np.abs(np.log(CONTEXP014_AM241_00595/757.66)/-0.746)
print(f'equação exponencial - espessura 1.4 mm:{XXX4_EXP_AM014}')


equação linear - espessura 0.2 mm:0.4543333333333332
equação linear - espessura 0.8 mm:0.2913703703703702
equação linear - espessura 1.4 mm:1.6543333333333332
equação quadrática - primeira raiz:-0.48006001378122254
equação quadrática - segunda raiz:1.608227501810302
equação exponencial - espessura 0.2 mm:0.43426199631847223
equação exponencial - espessura 0.8 mm:0.3307347202648661
equação exponencial - espessura 1.4 mm:1.6334968959069114


In [52]:
# (I/I0) - (inverso) EXP - VALOR 1 (AM241 - EXP) (PICO 1 - 59.5 KEV)

# EQUAÇÃO E COEF PEARSON - CALCULO ESPESSURA #

################################################################################################################################

"EQUAÇÃO LINEAR"

################################################################################################################################

# R**2 = 0.7116

#YINV01_EXP_AM002=1.3065*X_002+0.5345
#print(YINV01_EXP_AM002)
#YINV01_EXP_AM008=1.3065*X_008+0.5345
#print(YINV01_EXP_CS008)
#YINV01_EXP_AM014=1.3065*X_014+0.5345
#print(YINV01_EXP_AM014)

XINV1_EXP_AM002 = np.abs((np.log(PICOEXP_PLAAM002_00595)-0.5345)/(1.3065))
print(f'equação linear - espessura 0.2 mm:{XINV1_EXP_AM002}')
XINV1_EXP_AM008 = np.abs((np.log(PICOEXP_PLAAM008_00595)-0.5345)/(1.3065))
print(f'equação linear - espessura 0.2 mm:{XINV1_EXP_AM008}')
XINV1_EXP_AM014 = np.abs((np.log(PICOEXP_PLAAM014_00595)-0.5345)/(1.3065))
print(f'equação linear - espessura 0.2 mm:{XINV1_EXP_AM014}')


###############################################################################################################################

"EQUAÇÃO LOGARITMICA"

################################################################################################################################

# R**2 = 0.4479

#YINV2_EXP_AM002=0.6413*np.log(X_002)+1.8995
#print(YINV2_EXP_AM002)
#YINV2_EXP_AM008=0.6413*np.log(X_008)+1.8995
#print(YINV2_EXP_AM008)
#YINV2_EXP_AM014=0.6413*np.log(X_014)+1.8995
#print(YINV2_EXP_AM014)

# NÃO TEM VALOR PRA ESSA EQUAÇÃO #


################################################################################################################################

"EQUAÇÃO QUADRÁTICA"

################################################################################################################################

# R**2 = 1

#YINV3_EXP_AM002 = 2.4013*X_002**2-2.5356*X_002+1.495
#print(YINV3_EXP_AM002)
#YINV3_EXP_AM008 = 2.4013*X_008**2-2.5356*X_008+1.495
#print(YINV3_EXP_AM008)
#YINV3_EXP_AM014 = 2.4013*X_014**2-2.5356*X_014+1.495
#print(YINV3_EXP_AM014)

xINV3_EXP_AM1 = 0.5279640194894433
print(f'equação quadrática - primeira raiz:{xINV3_EXP_AM1}')
xINV3_EXP_AM2 = 0
print(f'equação quadrática - segunda raiz:{xINV3_EXP_AM2}')

################################################################################################################################

"EQUAÇÃO EXPONENCIAL"

################################################################################################################################

# R**2 = 0.6857

#YINV4_EXP_AM002=0.784*np.exp(0.7455*X_002)
#print(YINV4_EXP_AM002)
#YINV4_EXP_AM008=0.784*np.exp(0.7455*X_008)
#print(YINV4_EXP_AM008)
#YINV4_EXP_AM014=0.784*np.exp(0.7455*X_014)
#print(YINV4_EXP_AM014)

# NÃO TEM VALOR PRA ESSA EQUAÇÃO #



equação linear - espessura 0.2 mm:0.47080293334453066
equação linear - espessura 0.2 mm:0.4116897699798234
equação linear - espessura 0.2 mm:1.1555555051722963
equação quadrática - primeira raiz:-2.3432179679857383
equação quadrática - segunda raiz:5.743500853417138


'EQUAÇÃO EXPONENCIAL'

In [53]:
# Ln(I/I0) - (inverso) EXP - VALOR 1 (AM241 - EXP) (PICO 1 - 59.5 KEV)

# EQUAÇÃO E COEF PEARSON - CALCULO ESPESSURA #

################################################################################################################################

"EQUAÇÃO LINEAR"

################################################################################################################################

# R**2 = 0.6857

#YYINV1_EXP_AM002=0.7455*X_002-0.2433
#print(YYINV1_AM002)
#YYINV1_EXP_AM008=0.7455*X_008-0.2433
#print(YYINV1_EXP_AM008)
#YYINV1_EXP_AM014=0.7455*X_014-0.2433
#print(YYINV1_EXP_AM014)

XXINV1_EXP_CS002 = np.abs((np.log(PICOEXP_PLACS002_0662)+0.0184)/(0.1188))
print(XXINV1_EXP_CS002)
XXINV1_EXP_CS008 = np.abs((np.log(PICOEXP_PLACS008_0662)+0.0184)/(0.1188))
print(XXINV1_EXP_CS008)
XXINV1_EXP_CS014 = np.abs((np.log(PICOEXP_PLACS014_0662)+0.0184)/(0.1188))
print(XXINV1_EXP_CS014)

################################################################################################################################

"EQUAÇÃO LOGARITMICA"

################################################################################################################################

# R**2 = 0.4498

#YYINV2_EXP_AM002=0.3616*np.log(X_002)+0.5334
#print(YYINV2_EXP_AM002)
#YYINV2_EXP_AM008=0.3616*np.log(X_008)+0.5334
#print(YYINV2_EXP_AM008)
#YYINV2_EXP_AM014=0.3616*np.log(X_014)+0.5334
#print(YYINV2_EXP_AM014)

# NÃO TEM VALOR PRA ESSA EQUAÇÃO #


################################################################################################################################

"EQUAÇÃO QUADRÁTICA"

################################################################################################################################

# R**2 = 1

#YYINV3_EXP_AM002 = 1.4571*X_002**2-1.5858*X_002+0.3395
#print(YYINV3_EXP_AM002)
#YYINV3_EXP_AM008 = 1.4571*X_008**2-1.5858*X_008+0.3395
#print(YYINV3_EXP_AM008)
#YYINV3_EXP_AM014 = 1.4571*X_014**2-1.5858*X_014+0.3395
#print(YYINV3_EXP_AM014)

xxINV3_EXP_AM1 = 0.7953928207641846
print(f'equação quadrática - primeira raiz:{xxINV3_EXP_AM1}')
xxINV3_EXP_AM2 = 0.29293330647485183
print(f'equação quadrática - segunda raiz:{xxINV3_EXP_AM2}')


################################################################################################################################

"EQUAÇÃO EXPONENCIAL"

############################################################################################################################

# NÃO TEM VALOR PRA ESSA EQUAÇÃO #

0.18243830821492393
0.6361809592141136
1.01733700100681
equação quadrática - primeira raiz:0.7953928207641846
equação quadrática - segunda raiz:0.29293330647485183


'EQUAÇÃO EXPONENCIAL'

In [ ]:
################################################################################################################################


# FEIXE PENCIL BEAM #


################################################################################################################################

In [56]:
# LN(I/I0) EXP - VALOR 2 (CS137 - PBEAM) (PICO 1 - 662 KEV)

################################################################################################################################


# [-0.00327367  0.0939783   0.13925964]


################################################################################################################################


# COEF A

a2=0.11877775833333334

# COEF B

b2=-0.018367450000000007

# ERRO

erro_a2= 0.020415991608631685

erro_b2= 0.019151897758709787


In [ ]:
# I/I0 PBEAM - VALOR 1 (CS137 - PBEAM) (PICO 1 - 662 KEV)

# EQUAÇÃO E COEF PEARSON - CALCULO ESPESSURA #

################################################################################################################################

"EQUAÇÃO LINEAR"

################################################################################################################################

# R**2 = 0.9994

#Y1_PBEAM_CS002=-0.1038*X_002+0.9994
#print(Y1_PBEAM_CS002)
#Y1_PBEAM_CS008=-0.1038*X_008+0.9994
#print(Y1_PBEAM_CS008)
#Y1_PBEAM_CS014=-0.1038*X_014+0.9994
#print(Y1_PBEAM_CS014)

X1_PBEAM_CS002=np.abs((PICOPBEAM_PLACS002_0662-0.9994)/-0.1038)
print(f'equação linear - espessura 0.2 mm: {X1_PBEAM_CS002}')
X1_PBEAM_CS008=np.abs((PICOPBEAM_PLACS008_0662-0.9994)/-0.1038)
print(f'equação linear - espessura 0.8 mm: {X1_PBEAM_CS008}')
X1_PBEAM_CS014=np.abs((PICOPBEAM_PLACS014_0662-0.9994)/-0.1038)
print(f'equação linear - espessura 1.4 mm: {X1_PBEAM_CS014}')


################################################################################################################################

"EQUAÇÃO LOGARITMICA"

################################################################################################################################

# R**2 = 0.412

# Y2_EXP_AM002=-0.217*np.log(X_002)+0.6573
# print(Y2_EXP_AM002)
# Y2_EXP_AM008=-0.217*np.log(X_008)+0.6573
# print(Y2_EXP_AM008)
# Y2_EXP_AM014=-0.217*np.log(X_014)+0.6573
# print(Y2_EXP_AM014)

################################################################################################################################

"EQUAÇÃO QUADRÁTICA"

################################################################################################################################

# R**2 = 1

#Y3_EXP_AM002 = -0.9633*X_002**2+1.0868*X_002+0.7437
#print(Y3_EXP_AM002)
#Y3_EXP_AM008 = -0.9633*X_002**2+1.0868*X_008+0.7437
#print(Y3_EXP_AM008)
#Y3_EXP_AM014 = -0.9633*X_002**2+1.0868*X_014+0.7437
#print(Y3_EXP_AM014)

x3_EXP_AM1 = -0.4800455753914926
print(f'equação quadrática - primeira raiz:{x3_EXP_AM1}')
x3_EXP_AM2 = 1.6082507035966
print(f'equação quadrática - segunda raiz:{x3_EXP_AM2}')

################################################################################################################################

"EQUAÇÃO EXPONENCIAL"

################################################################################################################################


# R**2 = 0.6857

#Y4_EXP_AM002=1.2755*np.exp(-0.746*X_002)
#print(Y4_EXP_AM002)
#Y4_EXP_AM008=1.2755*np.exp(-0.746*X_008)
#print(Y4_EXP_AM008)
#Y4_EXP_AM014=1.2755*np.exp(-0.746*X_014)
#print(Y4_EXP_AM014)

X4_EXP_AM002=(np.log(PICOEXP_PLAAM002_00595/1.2755)/(-0.746))
print(f'equação exponencial - espessura 0.2 mm:{X4_EXP_AM002}')
X4_EXP_AM008=(np.log(PICOEXP_PLAAM008_00595/1.2755)/(-0.746))
print(f'equação exponencial - espessura 0.2 mm:{X4_EXP_AM008}')
X4_EXP_AM014=(np.log(PICOEXP_PLAAM014_00595/1.2755)/(-0.746))
print(f'equação exponencial - espessura 0.2 mm:{X4_EXP_AM014}')

In [57]:
# LN(I/I0) EXP - VALOR 3 (CS137 - EXP) (PICO 1 - 662 KEV)
################################################################################################################################


# [-0.08060403 -0.00337268 -0.97523327]
################################################################################################################################

# COEF A

a1=-0.11877775833333334

# COEF B

b1=0.018367450000000007

# ERRO

erro_a1= 0.0204159

erro_b1= 0.01915189
